# Runs eslint --fix and prettier --write on push to main, then commits
# any auto-fixes back to the branch using the built-in GITHUB_TOKEN.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Format

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  lint-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Lint source files
        run: yarn lint

      - name: Format source files
        run: yarn format

      - name: Commit any changes due to lint and format
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_name: GitHub Action
          message: changes by lint&format script [skip ci]
          push: origin main
